# environment defaults internally to development
# however, consumers can override it using a custom values file.
environment: development
serviceAccount:
  name: ndtech-website
deployment:
  replicas: 1
  minReadySeconds: 3
  namespace: ndtech
  imageVersion: 0.0.3
  containerPort: 3000
  githubClientId: 8579c818edb32a099c96